var express = require("express");
var router  = express.Router();
var auth = require(ROOT_FOLDER + "/middlewares/authentication");
var productController = require(ROOT_FOLDER + "/controllers/api/v1/user/product");
var sController = require(ROOT_FOLDER + "/controllers/api/v1/user/seller");
router.get("/get-products", productController.getProducts);
router.get("/popular", productController.getPopularProducts);
router.get("/best-sellers", productController.getBestSellers);
router.get("/best-offers", productController.getBestOffers);
router.get("/top-rated", productController.getTopRated);
router.get("/get-single-product/:id", productController.getSingleProduct);
router.get("/by/seller/:id", productController.getProductsBySeller);
router.get("/by/seller/:id/top-products", sController.getTopProducts);
router.get("/check-review/:id/:oid",auth.partialAuthenticate, productController.checkReviewProduct);
router.post("/save-review/:id/:oid",auth.partialAuthenticate, productController.saveReview);
router.get("/get-review/:id", productController.getSingleProductReview);
router.get("/get-returnproduct/:id/:oid",auth.partialAuthenticate, productController.getSingleProductReturn);
router.post("/add-return/:id/:oid",auth.partialAuthenticate, productController.saveReturn);
module.exports = router;
